name: MapArtist
version: '${version}'

main: io.github.willits.mapArtist.MapArtist
api-version: '1.21'

authors: [ wildcat ]

commands:
  mapartist:
    description: MapArtist commands
    usage: /mapartist <draw|brush|give|reload|confirm|cancel|setowner|unlock>
    aliases: [ ma ]
    permission: mapartist.use

permissions:
  mapartist.use:
    description: Allows using MapArtist
    default: true
  mapartist.admin:
    description: Allows admin commands
    default: op
